function rec_data_mV = measure_calibration_stimuli(ex, calibration_stim, trigger_stim)
%% Handles calibration-related variables needed to run present_sound()
% Create block of calibration stimuli
calibration_stim = repmat(calibration_stim,10,1);
trigger_stim = repmat(trigger_stim,10,1);
stimulus = cat(3,calibration_stim,trigger_stim);

% Initialize present_sound variables
[~, ~, ~, ...
    output_channels, input_channels, ...
    DAC_conversion_factor, ~, ~, ...
    hydrophone_idx, ~, ~, ~] ...
    = init_present_sound_variables(ex, stimulus(:,:,1));

% Present sound
rec_data_mV = present_sound(stimulus, ...
    input_channels, output_channels, ...
    hydrophone_idx, DAC_conversion_factor);
end