function ex = setup_info(ex)

t = datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd HH:mm:ss');
rng('default')

ex.info.experiment = struct( ...
    'facility_name',         'Sisneros Laboratory', ...
    'experimenter_name',     'Aoi Hunsaker', ...
    'exp_date',              datestr(t, 'yyyy-mm-dd'), ...
    'exp_time_start',        datestr(t, 'HH:MM:SS'), ...      
    'exp_time_end',          NaN, ... % Will be assigned in finish_experiment
    'exp_duration',          NaN, ... % Will be assigned in finish_experiment  
    'drug_name',             'Anesthetic: Benzocaine sulfate; Paralytic: Cisatracurium besylate', ...
    'drug_delivery_method',  'Anesthetic: Bath; Paralytic: Injection', ...      % bath / injection / none
    'drug_concentration',    'Anesthetic: 0.025% ; Paralytic: 3 mg kg−1 ', ...
    'water_salinity',        NaN, ... 
    'water_depth',           'Need to measure', ...
    'tank_dimensions',       'X liter circular tank (X mm inside diameter)', ...
    'tank_material',         'High density polyethelene', ...
    'tank_isolation_method', 'Floating table', ...
    'noise_floor',           NaN, ... % Measure during setup
    'random_seed',           "default" ...
);

ex.info.animal = struct( ...
    'species_name',          'hydrolgus_colliei', ...
    'subject_ID',            NaN, ... % In app
    'sex',                   NaN, ... % In app
    'standard_length_mm',    NaN, ... % Enter manually in finish_experiment.m
    'body_mass_g',           NaN, ... % Enter manually in finish_experiment.m
    'developmental_stage',   'adult', ... 
    'health_note',           '', ... % In app
    'source',                'via trawl at San Juan Island Friday Harbor', ...
    'collection_date',       '2026-03-02', ...
    'housing',               'Indoor holding tanks', ...
    'diet',                  'Mixed diet shrimp and squid', ...
    'acclimation_period',    '1 day', ...
    'IACUC_protocol_ID',     'University of Washington Animal Care and Use Committee', ...
    'Collection permit',     'Washington State Scientific Collection Permit from Department of Fish and Wildlife', ...
    'filename',              string() ... % Auto generate here
);

ex.info.stimulus = struct( ...
    'frequency_hz',                         NaN, ... % In app
    'amplitude_spl',                         140, ... % dB SPL re 1 micro Pascal, Value changes later in prepare_next_amp
    'type',                              'tone burst', ...
    'polarity',                          'alternating', ...
    'starting_amp_spl',                      140, ... % Set in app (140)
    'waveform',                          NaN, ...
    'ramp_type',                         'Hanning', ...
    'full_amplitude_duration_ms',           50, ... % (ms) Nieder et al. 2023, check the spectra of this to make sure it is not too broadband
    'ramp_duration_ms',                   10, ... % Set in app (10 ms)
    'total_stimulus_duration_ms',           NaN, ...
    'speaker_model',                     'UW-30 Lubell Labs Inc., Columbus, OH, USA Serial #', ...
    'max_amplitude_limit',               140, ...
    'speaker_orientation',               'centered under fish', ...
    'speaker_distance_from_head',        NaN, ... % Determine later
    'calibration',                       NaN, ... % output from calibration GUI will generate this
    'calibration_file_name',             '' ... % auto generate here
);

ex.info.channels = struct( ...
    'n_channels',            4, ...
    'names',         {{'L','R','Forebrain','Abdomen'}}, ...
    'reference_location',    'tail', ...
    'ground_location',       'in water', ...
    'electrode_type',        'Subdermal, differential measurment, stainless steel, 27 gauge, 13 mm, Rochester Electromedical Inc.; Coral Springs, FL, USA', ...
    'electrode_depth',       '3 mm' ...
);

ex.info.recording = struct( ...
    'sampling_rate_hz',          2000, ... % check with Andrew that this is a good rate
    'ADC_bit_depth',             NaN, ...
    'voltage_scaling_factor_V',  5.124, ... % in volts double check that this is the factor!
    'latency_samples',           NaN, ... % will be populated later
    'DAC_model_serial',          'USB D/A Converter, Fireface UCX, RME, Frankfurt, Germany', ...
    'DAC_output_channels',       [1 4], ...
    'DAC_output_channel_names',  {'UW30', 'Loopback'}, ...
    'DAC_input_channels',        [3:8], ...
    'DAC_input_channel_names',   {'Hydrophone', 'Loopback', 'Ch1', 'Ch2','Ch3','Ch4'}, ...
    'hydrophone_model',          'Type 8103, Bruel & Kjaer, Nærum, Denmark, Serial #: ', ...
    'hydrophone_gain_mV_per_Pa', 100, ...
    'bioamplifier_model_serial', 'BMA-400, CWE Inc. Ardmore, PA, USA', ...
    'bioamp_gain',               10000, ...
    'audio_amplifier',           'Power amplifier, Crown D75-A, Harman, Northridge, CA, USA', ...
    'amplifier_gain',            'Need to measure' ...
);

ex.info.adaptive = struct( ...
    'response_feature',                   'double_frequency_response', ... % Make this an if statement so it will generate which frequency to look for in the response
    'target_response_frequency',           ex.info.stimulus.frequency*2, ... % Auto populate
    'trials_per_block',                    20, ... % Set in GUI
    'max_trials',                          1000 ... % Set in GUI
);

ex.info.signal_quality = struct( ...
    'filter_type',               'butterworth', ...
    'bandpass_low_Hz',           40, ...
    'bandpass_high_Hz',          1000, ...
    'artifact_detection_method', 'standard deviation', ...
    'rejection_threshold_sd',    3 ...
);

ex.info.model = struct( ... % These values will be updated by prepare_next_amplitude when new amplitude is selected
    'initial_x0',         130, ...
    'initial_kappa',      1, ...
    'initial_lambda',     1, ...
    'initial_max_resp',   5, ...
    'response_fn',        @(params, x) (params(3) ./ (1 + exp(-params(2) * (x - params(1))))) .* params(4), ...
    'initial_x_vector',           NaN, ...
    'initial_y_vector',           NaN ...
    );

% ex.info.fft?
