function ex = setup_stimulus_info(ex,app)

% Get list of stimulus frequencies
if strcmp(ex.info.experiment.exp_type, 'Mixed freqs')
    freq_vec = ex.info.mixed.stim_freqs;
else
    freq_vec = app.EditField_frequency.Value;
end

% Preallocate
for ifreq = 1:length(freq_vec)
    % Stimulus
    ex.info.stimulus(ifreq) = struct( ...
        'frequency_hz',                         freq_vec(ifreq), ... % In app
        'amplitude_spl',                        NaN, ... % dB SPL re 1 micro Pascal, Value changes later in prepare_next_amp
        'spl_reference',                        '1 micro Pascal', ... % dB SPL re 1 micro Pascal, Value changes later
        'type',                                 app.DropDown_tone_burst.Value, ... % Set in GUI
        'polarity',                             'alternating', ...
        'waveform',                             NaN, ...
        'ramp_type',                            'cosine', ...
        'full_amplitude_cycle_num',             6, ...
        'full_amplitude_duration_ms',           NaN, ...
        'ramp_duration_cycles',                 6, ...
        'ramp_duration_ms',                     NaN, ...
        'range_2f_hz',                          3, ... % +/- 3 Hz above and below the double frequency response point
        'desired_freq_res',                     5, ...
        'trim_stim_pre_dur_ms',                 5 ...
        );

    % Calibration
    ex.info.calibration(ifreq) = struct( ...
        'hydrophone_amplitude_convention',   'SPL', ...
        'target_amp_spl',                     130, ...
        'correction_factor_dB',               NaN, ...
        'correction_factor_linear',           NaN, ...
        'correction_tolerance_dB',            3, ...
        'signals',                            NaN, ...
        'initial_calibration_complete',       NaN, ...
        'check_passed',                       NaN, ...
        'uncorrected_levels',                 NaN, ...
        'corrected_level',                    NaN, ...
        'time_vector',                        NaN, ...
        'time_sig',                           NaN, ...
        'freq_vec',                           NaN, ...
        'fft_vals',                           NaN, ...
        'snr',                                NaN ...
        );
end